*** Variable ***
${CSV_DELIMITER}=   ___
${BROSWER}=  %{DEFAULT_BROWSER}
${F_URL}=  %{FRONTEND_URL}
${USER}=  %{USERNAME}
${LOCK_USER}=  %{LOCKEDOUTUSER}
${PROBLEM_USER}=  %{PROBLEMUSER}
${PERFORMANCE_USER}=  %{PERFORMANCEUSER}
${PASSWORD}=  %{PASS}

